---
- name: Install wireguard
  become: yes
  apt:
    pkg:
    - wireguard
    state: present

- name: Ensure packet forwarding is enabled
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

